# SPDX-License-Identifier: Apache-2.0

CONFIG_MEMC=y
CONFIG_MEMC_SF32LB_MPI_OPI_PSRAM=y
CONFIG_LOG=y
CONFIG_MEMC_LOG_LEVEL_INF=y

# Regulator support for PSRAM LDO
CONFIG_REGULATOR=y
CONFIG_REGULATOR_SF32LB_LDO=y
